//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatBritainApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public string NameProizv { get; set; }
        public string date { get; set; }
    }
}
