//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatBritainApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productxlsx
    {
        public int Id { get; set; }
        public string Product { get; set; }
        public Nullable<int> Amount { get; set; }
        public string DateSale { get; set; }
    }
}
