//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatBritainApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productcsv
    {
        public string NameProduct { get; set; }
        public string image { get; set; }
        public string manufacturer { get; set; }
        public string Activen { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
