//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pooshreniya
    {
        public int ID { get; set; }
        public string Motiv { get; set; }
        public string Vid { get; set; }
        public System.DateTime Date { get; set; }
        public string Osnovaniya { get; set; }
        public decimal Summa { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
