//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testim
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    public partial class Sotrudniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudniki()
        {
            this.Med_obsledovaniya = new HashSet<Med_obsledovaniya>();
            this.Otpuskas = new HashSet<Otpuska>();
            this.Pooshreniyas = new HashSet<Pooshreniya>();
            this.Komandirovkis = new HashSet<Komandirovki>();
            this.Soc_lgoti = new HashSet<Soc_lgoti>();
            this.Uvolneniyas = new HashSet<Uvolneniya>();
        }
        public string GetPhoto
        {
            get
            {
                if (Photo is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + Photo.Trim();
            }
        }
        public int Id_Sotrudnika { get; set; }
        public string Photo { get; set; }
        public string Second_name { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Pol { get; set; }
        public string Semeynoe_polozhenie { get; set; }
        public Nullable<System.DateTime> Date_birthday { get; set; }
        public Nullable<System.DateTime> Data_priema { get; set; }
        public Nullable<double> Stazh { get; set; }
        public string Telephone { get; set; }
        public string Adres { get; set; }
    
        public virtual Dolzgnost Dolzgnost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Med_obsledovaniya> Med_obsledovaniya { get; set; }
        public virtual Otdel Otdel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otpuska> Otpuskas { get; set; }
        public virtual Pasportnie_dannie Pasportnie_dannie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pooshreniya> Pooshreniyas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komandirovki> Komandirovkis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soc_lgoti> Soc_lgoti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uvolneniya> Uvolneniyas { get; set; }
    }
}
