//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uvolneniya
    {
        public int ID_Sotrudnika { get; set; }
        public System.DateTime Date_uvolneniya { get; set; }
        public string Prichina { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
