//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Variant7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shtatnoe_raspisanie
    {
        public int ID { get; set; }
        public string Kolvo_sotrudnikov { get; set; }
    
        public virtual Dolzgnost Dolzgnost { get; set; }
        public virtual Otdel Otdel { get; set; }
    }
}
