//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JekaStudying
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soc_lgoti
    {
        public int ID_Sotrudnika { get; set; }
        public string Name_lgot { get; set; }
        public double nomer_documenta { get; set; }
        public System.DateTime Data_vidachi_documenta { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
