//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasportnie_dannie
    {
        public int ID_Sotrudnika { get; set; }
        public double Nomer_pasporta { get; set; }
        public double Seriya_pasporta { get; set; }
        public string Kem_vidan { get; set; }
        public System.DateTime Kogda_vidan { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
