//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Счет = new HashSet<Счет>();
        }
    
        public int NumberOrder { get; set; }
        public string Duration { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> Id_Yslugi { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public Nullable<int> DateConclusion { get; set; }
        public string Photo { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Услуги Услуги { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Счет> Счет { get; set; }
    }
}
