//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оборудование
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Оборудование()
        {
            this.Услуги = new HashSet<Услуги>();
        }
    
        public int IDEquipment { get; set; }
        public string Name { get; set; }
        public string Processor { get; set; }
        public string RAM { get; set; }
        public string DiskArray { get; set; }
        public string NetworkCard { get; set; }
        public string VideoCard { get; set; }
        public string OS { get; set; }
        public Nullable<double> ProcessorClockSpeed { get; set; }
        public Nullable<int> TotalPhysicalMemory { get; set; }
        public Nullable<int> AmountRAM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Услуги> Услуги { get; set; }
    }
}
