//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оплата
    {
        public int IdPayment { get; set; }
        public Nullable<System.DateTime> DatePayment { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> NumberAccount { get; set; }
    
        public virtual Счет Счет { get; set; }
    }
}
