//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Счет
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Счет()
        {
            this.Оплата = new HashSet<Оплата>();
        }
    
        public int NumberAccount { get; set; }
        public string DateDischarge { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public string NotePayment { get; set; }
        public Nullable<int> NumberOrder { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оплата> Оплата { get; set; }
    }
}
