//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edickss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dolzgnost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dolzgnost()
        {
            this.Shtatnoe_raspisanie = new HashSet<Shtatnoe_raspisanie>();
            this.Sotrudnikis = new HashSet<Sotrudniki>();
        }
    
        public int ID_Dolzgnosti { get; set; }
        public string Dolzgnost1 { get; set; }
        public double Oklad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shtatnoe_raspisanie> Shtatnoe_raspisanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sotrudniki> Sotrudnikis { get; set; }
    }
}
