//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edickss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otpuska
    {
        public int ID { get; set; }
        public string Vid_otpuska { get; set; }
        public System.DateTime Data_otpuska { get; set; }
        public double Kolvo_dney { get; set; }
        public Nullable<double> Dni_dop { get; set; }
        public System.DateTime Data_okonchaniya { get; set; }
        public string Osnovaniya { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
