//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadyProduct
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductDBEntities1 : DbContext
    {
        private static ProductDBEntities1 _context;
        public ProductDBEntities1()
            : base("name=ProductDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static ProductDBEntities1 GetContext()
        {
            if (_context == null)
                _context = new ProductDBEntities1();
            return _context;
        }
        public virtual DbSet<Basket> Baskets { get; set; }
        public virtual DbSet<Buyer> Buyers { get; set; }
        public virtual DbSet<Check> Checks { get; set; }
        public virtual DbSet<Payment_type> Payment_type { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type_product> Type_product { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
