//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSash
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SashEntities6 : DbContext
    {
        private static SashEntities6 _context;
        public SashEntities6()
            : base("name=SashEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static SashEntities6 GetContext()
        {
            if (_context == null)
                _context = new SashEntities6();
            return _context;
        }
        public virtual DbSet<Auto> Autoes { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<SelledAuto> SelledAutoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeAuto> TypeAutoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
