//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSash
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelledAuto
    {
        public int Id_prokat { get; set; }
        public Nullable<System.DateTime> DateVidacha { get; set; }
        public Nullable<int> CountDays { get; set; }
        public Nullable<decimal> Summ { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual Client Client { get; set; }
    }
}
