//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdam
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowerZakaz
    {
        public int IDZakaza { get; set; }
        public string Kolichestvo { get; set; }
        public int FlowerID { get; set; }
    
        public virtual Flower Flower { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
