//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellBooks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProdaSEntities1 : DbContext
    {
        private static ProdaSEntities1 _context;
        public ProdaSEntities1()
            : base("name=ProdaSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static ProdaSEntities1 GetContext()
        {
            if (_context == null)
                _context = new ProdaSEntities1();
            return _context;
        }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Жанр> Жанр { get; set; }
        public virtual DbSet<Издательство> Издательство { get; set; }
        public virtual DbSet<Продажи> Продажи { get; set; }
    }
}
