//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellBooks
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    public partial class Продажи
    {
        public string GetPhoto
        {
            get
            {
                if (Photo is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + Photo.Trim();
            }
        }
        public int IdSell { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string NameBook { get; set; }
        public string Author { get; set; }
        public int IdGenre { get; set; }
        public int IdPublish { get; set; }
        public Nullable<double> Price { get; set; }
        public string DatePublish { get; set; }
        public string Photo { get; set; }
    
        public virtual Жанр Жанр { get; set; }
        public virtual Издательство Издательство { get; set; }
    }
}
